### ISSUE TITLE
Загрузка docx или pdf курсовой работы в портфолио сайта РУТ (МИИТ)

### ISSUE THREAD

**Issue by FlashAnton** [aosihgaweeff/-#12]
Здравствуйте.

Одно небольшое незавершённое дело осталось по курсу "Методы программирования".
Загрузите, пожалуйста, свои отчёты по курсовой работе в портфолио на сайт.

Темой указывать: "Методы программирования электронного документооборота".

По исполнении, пожалуйста, отпишитесь.

Заранее благодарю.

**Comment by aosihgaweeff** [comment]
Здравствуйте. Мы загрузили отчеты.

**Comment by FlashAnton** [comment]
Здравствуйте.

Спасибо. Всё увидел. Рецензией результаты зафиксировал.
